pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r Projects/flask-app/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'python tests.py'
            }
        }
        stage('Deploy') {
            steps {
                sh 'python app.py'
            }
        } 
    }
    post { 
      always { 
         archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
       } 
   } 
}